# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\ui_dialog_preferences.ui'
#
# Created: Fri Nov 28 12:49:12 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPreferences(object):
    def setupUi(self, DialogPreferences):
        DialogPreferences.setObjectName("DialogPreferences")
        DialogPreferences.resize(437, 345)
        self.gridLayout = QtWidgets.QGridLayout(DialogPreferences)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonOk = QtWidgets.QPushButton(DialogPreferences)
        self.buttonOk.setObjectName("buttonOk")
        self.horizontalLayout.addWidget(self.buttonOk)
        self.buttonClose = QtWidgets.QPushButton(DialogPreferences)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.buttonApply = QtWidgets.QPushButton(DialogPreferences)
        self.buttonApply.setObjectName("buttonApply")
        self.horizontalLayout.addWidget(self.buttonApply)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 2, 1)
        self.tabWidget = QtWidgets.QTabWidget(DialogPreferences)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_general)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_general)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 385, 233))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.pref_general_path_dir_arch = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.pref_general_path_dir_arch.setObjectName("pref_general_path_dir_arch")
        self.gridLayout_3.addWidget(self.pref_general_path_dir_arch, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.pref_general_path_dir_maps = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.pref_general_path_dir_maps.setInputMask("")
        self.pref_general_path_dir_maps.setFrame(True)
        self.pref_general_path_dir_maps.setObjectName("pref_general_path_dir_maps")
        self.gridLayout_3.addWidget(self.pref_general_path_dir_maps, 1, 1, 1, 1)
        self.fileChooser_pref_general_path_dir_maps = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        self.fileChooser_pref_general_path_dir_maps.setObjectName("fileChooser_pref_general_path_dir_maps")
        self.gridLayout_3.addWidget(self.fileChooser_pref_general_path_dir_maps, 1, 2, 1, 1)
        self.fileChooser_pref_general_path_file_editor = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        self.fileChooser_pref_general_path_file_editor.setObjectName("fileChooser_pref_general_path_file_editor")
        self.gridLayout_3.addWidget(self.fileChooser_pref_general_path_file_editor, 2, 2, 1, 1)
        self.pref_general_path_file_editor = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.pref_general_path_file_editor.setObjectName("pref_general_path_file_editor")
        self.gridLayout_3.addWidget(self.pref_general_path_file_editor, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.fileChooser_pref_general_path_dir_arch = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        self.fileChooser_pref_general_path_dir_arch.setObjectName("fileChooser_pref_general_path_dir_arch")
        self.gridLayout_3.addWidget(self.fileChooser_pref_general_path_dir_arch, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.pref_general_fix = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.pref_general_fix.setStyleSheet("margin-left: 10;")
        self.pref_general_fix.setObjectName("pref_general_fix")
        self.gridLayout_6.addWidget(self.pref_general_fix, 3, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_filters)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_filters)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 385, 233))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pref_filters_error_level_low = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.pref_filters_error_level_low.setStyleSheet("margin-left: 10;")
        self.pref_filters_error_level_low.setObjectName("pref_filters_error_level_low")
        self.gridLayout_5.addWidget(self.pref_filters_error_level_low, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.pref_filters_error_level_warning = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.pref_filters_error_level_warning.setStyleSheet("margin-left: 10;")
        self.pref_filters_error_level_warning.setObjectName("pref_filters_error_level_warning")
        self.gridLayout_5.addWidget(self.pref_filters_error_level_warning, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.pref_filters_error_level_critical = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.pref_filters_error_level_critical.setStyleSheet("margin-left: 10;")
        self.pref_filters_error_level_critical.setObjectName("pref_filters_error_level_critical")
        self.gridLayout_5.addWidget(self.pref_filters_error_level_critical, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 7, 0, 1, 1)
        self.pref_filters_error_level_medium = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.pref_filters_error_level_medium.setStyleSheet("margin-left: 10;")
        self.pref_filters_error_level_medium.setObjectName("pref_filters_error_level_medium")
        self.gridLayout_5.addWidget(self.pref_filters_error_level_medium, 4, 0, 1, 1)
        self.pref_filters_error_level_high = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.pref_filters_error_level_high.setStyleSheet("margin-left: 10;")
        self.pref_filters_error_level_high.setObjectName("pref_filters_error_level_high")
        self.gridLayout_5.addWidget(self.pref_filters_error_level_high, 5, 0, 1, 1)
        self.pref_filters_ignore_event_maps = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        self.pref_filters_ignore_event_maps.setStyleSheet("margin-left: 10")
        self.pref_filters_ignore_event_maps.setObjectName("pref_filters_ignore_event_maps")
        self.gridLayout_5.addWidget(self.pref_filters_ignore_event_maps, 8, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 9, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_filters, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 385, 233))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pref_errors_decor_wall_l4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_decor_wall_l4.setStyleSheet("margin-left: 10;")
        self.pref_errors_decor_wall_l4.setObjectName("pref_errors_decor_wall_l4")
        self.gridLayout_8.addWidget(self.pref_errors_decor_wall_l4, 5, 0, 1, 1)
        self.pref_errors_decor_wall_l3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_decor_wall_l3.setStyleSheet("margin-left: 10;")
        self.pref_errors_decor_wall_l3.setObjectName("pref_errors_decor_wall_l3")
        self.gridLayout_8.addWidget(self.pref_errors_decor_wall_l3, 4, 0, 1, 1)
        self.pref_errors_sys_not_on_top = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_sys_not_on_top.setStyleSheet("margin-left: 10;")
        self.pref_errors_sys_not_on_top.setObjectName("pref_errors_sys_not_on_top")
        self.gridLayout_8.addWidget(self.pref_errors_sys_not_on_top, 6, 0, 1, 1)
        self.pref_errors_deprecated_control_chars = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_deprecated_control_chars.setStyleSheet("margin-left: 10;")
        self.pref_errors_deprecated_control_chars.setObjectName("pref_errors_deprecated_control_chars")
        self.gridLayout_8.addWidget(self.pref_errors_deprecated_control_chars, 7, 0, 1, 1)
        self.pref_errors_layer_changed = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_layer_changed.setStyleSheet("margin-left: 10;")
        self.pref_errors_layer_changed.setObjectName("pref_errors_layer_changed")
        self.gridLayout_8.addWidget(self.pref_errors_layer_changed, 8, 0, 1, 1)
        self.pref_errors_decor_wall_l2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_decor_wall_l2.setStyleSheet("margin-left: 10;")
        self.pref_errors_decor_wall_l2.setObjectName("pref_errors_decor_wall_l2")
        self.gridLayout_8.addWidget(self.pref_errors_decor_wall_l2, 3, 0, 1, 1)
        self.pref_errors_map_no_music = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_map_no_music.setStyleSheet("margin-left: 10;")
        self.pref_errors_map_no_music.setObjectName("pref_errors_map_no_music")
        self.gridLayout_8.addWidget(self.pref_errors_map_no_music, 2, 0, 1, 1)
        self.pref_errors_map_no_region = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.pref_errors_map_no_region.setStyleSheet("margin-left: 10;")
        self.pref_errors_map_no_region.setObjectName("pref_errors_map_no_region")
        self.gridLayout_8.addWidget(self.pref_errors_map_no_region, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_7.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(DialogPreferences)
        self.tabWidget.setCurrentIndex(0)
        self.buttonClose.clicked.connect(DialogPreferences.close)
        QtCore.QMetaObject.connectSlotsByName(DialogPreferences)

    def retranslateUi(self, DialogPreferences):
        _translate = QtCore.QCoreApplication.translate
        DialogPreferences.setWindowTitle(_translate("DialogPreferences", "Preferences"))
        self.buttonOk.setText(_translate("DialogPreferences", "Ok"))
        self.buttonClose.setText(_translate("DialogPreferences", "Cancel"))
        self.buttonApply.setText(_translate("DialogPreferences", "Apply"))
        self.label_9.setText(_translate("DialogPreferences", "<html><head/><body><p><span style=\" font-weight:600;\">Scan options</span></p></body></html>"))
        self.label_2.setText(_translate("DialogPreferences", "<html><head/><body><p><span style=\" font-weight:600;\">Paths</span></p></body></html>"))
        self.label_4.setText(_translate("DialogPreferences", "Arch"))
        self.label.setText(_translate("DialogPreferences", "Maps"))
        self.fileChooser_pref_general_path_dir_maps.setText(_translate("DialogPreferences", "..."))
        self.fileChooser_pref_general_path_file_editor.setText(_translate("DialogPreferences", "..."))
        self.label_3.setText(_translate("DialogPreferences", "Editor"))
        self.fileChooser_pref_general_path_dir_arch.setText(_translate("DialogPreferences", "..."))
        self.pref_general_fix.setText(_translate("DialogPreferences", "Automatically attempt to fix errors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("DialogPreferences", "General"))
        self.pref_filters_error_level_low.setText(_translate("DialogPreferences", "Low"))
        self.label_5.setText(_translate("DialogPreferences", "<b>Error levels</b>"))
        self.pref_filters_error_level_warning.setText(_translate("DialogPreferences", "Warning"))
        self.label_6.setText(_translate("DialogPreferences", "Show the following error levels:"))
        self.pref_filters_error_level_critical.setText(_translate("DialogPreferences", "Critical"))
        self.label_7.setText(_translate("DialogPreferences", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Miscellaneous</span></p></body></html>"))
        self.pref_filters_error_level_medium.setText(_translate("DialogPreferences", "Medium"))
        self.pref_filters_error_level_high.setText(_translate("DialogPreferences", "High"))
        self.pref_filters_ignore_event_maps.setText(_translate("DialogPreferences", "Ignore event maps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filters), _translate("DialogPreferences", "Filters"))
        self.pref_errors_decor_wall_l4.setText(_translate("DialogPreferences", "Layer 4 object on square with a wall"))
        self.pref_errors_decor_wall_l3.setText(_translate("DialogPreferences", "Layer 3 object on square with a wall"))
        self.pref_errors_sys_not_on_top.setText(_translate("DialogPreferences", "System object not on top of normal objects"))
        self.pref_errors_deprecated_control_chars.setText(_translate("DialogPreferences", "Check for deprecated control characters"))
        self.pref_errors_layer_changed.setText(_translate("DialogPreferences", "Layer changed from the default value"))
        self.pref_errors_decor_wall_l2.setText(_translate("DialogPreferences", "Layer 2 object on square with a wall"))
        self.pref_errors_map_no_music.setText(_translate("DialogPreferences", "Map with no music"))
        self.pref_errors_map_no_region.setText(_translate("DialogPreferences", "Map with no region"))
        self.label_8.setText(_translate("DialogPreferences", "Configure what kind of errors to check for."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogPreferences", "Errors"))

