# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/ui_window_interface_editor.ui'
#
# Created: Sun Mar 15 18:12:32 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WindowInterfaceEditor(object):
    def setupUi(self, WindowInterfaceEditor):
        WindowInterfaceEditor.setObjectName("WindowInterfaceEditor")
        WindowInterfaceEditor.resize(969, 641)
        self.centralwidget = QtWidgets.QWidget(WindowInterfaceEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.treeView = QtWidgets.QTreeView(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(100, 100))
        self.treeView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeView.setAnimated(True)
        self.treeView.setHeaderHidden(True)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_18.addWidget(self.treeView)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageNone = QtWidgets.QWidget()
        self.pageNone.setObjectName("pageNone")
        self.stackedWidget.addWidget(self.pageNone)
        self.pageChoice = QtWidgets.QWidget()
        self.pageChoice.setObjectName("pageChoice")
        self.stackedWidget.addWidget(self.pageChoice)
        self.pageSay = QtWidgets.QWidget()
        self.pageSay.setObjectName("pageSay")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.pageSay)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_37 = QtWidgets.QLabel(self.pageSay)
        self.label_37.setObjectName("label_37")
        self.gridLayout_22.addWidget(self.label_37, 0, 0, 1, 1)
        self.interface_element_say_text = QtWidgets.QPlainTextEdit(self.pageSay)
        self.interface_element_say_text.setObjectName("interface_element_say_text")
        self.gridLayout_22.addWidget(self.interface_element_say_text, 1, 0, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_22)
        self.stackedWidget.addWidget(self.pageSay)
        self.pageKill = QtWidgets.QWidget()
        self.pageKill.setObjectName("pageKill")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.pageKill)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.pageKill)
        self.label_35.setObjectName("label_35")
        self.gridLayout_21.addWidget(self.label_35, 0, 0, 1, 1)
        self.interface_element_kill_nrof = QtWidgets.QLineEdit(self.pageKill)
        self.interface_element_kill_nrof.setObjectName("interface_element_kill_nrof")
        self.gridLayout_21.addWidget(self.interface_element_kill_nrof, 0, 2, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_21)
        spacerItem1 = QtWidgets.QSpacerItem(20, 531, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.pageKill)
        self.pageClose = QtWidgets.QWidget()
        self.pageClose.setObjectName("pageClose")
        self.stackedWidget.addWidget(self.pageClose)
        self.pagePart = QtWidgets.QWidget()
        self.pagePart.setObjectName("pagePart")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pagePart)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_26 = QtWidgets.QLabel(self.pagePart)
        self.label_26.setObjectName("label_26")
        self.gridLayout_15.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.pagePart)
        self.label_27.setObjectName("label_27")
        self.gridLayout_15.addWidget(self.label_27, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem2, 0, 1, 1, 1)
        self.interface_element_part_uid = QtWidgets.QLineEdit(self.pagePart)
        self.interface_element_part_uid.setObjectName("interface_element_part_uid")
        self.gridLayout_15.addWidget(self.interface_element_part_uid, 0, 2, 1, 1)
        self.interface_element_part_name = QtWidgets.QLineEdit(self.pagePart)
        self.interface_element_part_name.setObjectName("interface_element_part_name")
        self.gridLayout_15.addWidget(self.interface_element_part_name, 1, 2, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_15)
        spacerItem3 = QtWidgets.QSpacerItem(20, 443, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.pagePart)
        self.pageInfo = QtWidgets.QWidget()
        self.pageInfo.setObjectName("pageInfo")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.pageInfo)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_28 = QtWidgets.QLabel(self.pageInfo)
        self.label_28.setObjectName("label_28")
        self.gridLayout_16.addWidget(self.label_28, 0, 0, 1, 1)
        self.interface_element_info_text = QtWidgets.QPlainTextEdit(self.pageInfo)
        self.interface_element_info_text.setObjectName("interface_element_info_text")
        self.gridLayout_16.addWidget(self.interface_element_info_text, 1, 0, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_16)
        self.stackedWidget.addWidget(self.pageInfo)
        self.pageItem = QtWidgets.QWidget()
        self.pageItem.setObjectName("pageItem")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pageItem)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_29 = QtWidgets.QLabel(self.pageItem)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.pageItem)
        self.label_31.setObjectName("label_31")
        self.gridLayout_17.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.pageItem)
        self.label_30.setObjectName("label_30")
        self.gridLayout_17.addWidget(self.label_30, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem4, 0, 1, 1, 1)
        self.interface_element_item_name = QtWidgets.QLineEdit(self.pageItem)
        self.interface_element_item_name.setObjectName("interface_element_item_name")
        self.gridLayout_17.addWidget(self.interface_element_item_name, 1, 2, 1, 1)
        self.interface_element_item_nrof = QtWidgets.QLineEdit(self.pageItem)
        self.interface_element_item_nrof.setObjectName("interface_element_item_nrof")
        self.gridLayout_17.addWidget(self.interface_element_item_nrof, 2, 2, 1, 1)
        self.interface_element_item_arch = QtWidgets.QLineEdit(self.pageItem)
        self.interface_element_item_arch.setObjectName("interface_element_item_arch")
        self.gridLayout_17.addWidget(self.interface_element_item_arch, 0, 2, 1, 1)
        self.interface_element_item_keep = QtWidgets.QCheckBox(self.pageItem)
        self.interface_element_item_keep.setObjectName("interface_element_item_keep")
        self.gridLayout_17.addWidget(self.interface_element_item_keep, 3, 2, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_17)
        spacerItem5 = QtWidgets.QSpacerItem(20, 456, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.pageItem)
        self.pageObject = QtWidgets.QWidget()
        self.pageObject.setObjectName("pageObject")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.pageObject)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem6, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.pageObject)
        self.label_33.setObjectName("label_33")
        self.gridLayout_18.addWidget(self.label_33, 1, 0, 1, 1)
        self.interface_element_object_name = QtWidgets.QLineEdit(self.pageObject)
        self.interface_element_object_name.setObjectName("interface_element_object_name")
        self.gridLayout_18.addWidget(self.interface_element_object_name, 1, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.pageObject)
        self.label_32.setObjectName("label_32")
        self.gridLayout_18.addWidget(self.label_32, 0, 0, 1, 1)
        self.interface_element_object_arch = QtWidgets.QLineEdit(self.pageObject)
        self.interface_element_object_arch.setObjectName("interface_element_object_arch")
        self.gridLayout_18.addWidget(self.interface_element_object_arch, 0, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.pageObject)
        self.label_41.setObjectName("label_41")
        self.gridLayout_18.addWidget(self.label_41, 2, 0, 1, 1)
        self.interface_element_object_remove = QtWidgets.QLineEdit(self.pageObject)
        self.interface_element_object_remove.setObjectName("interface_element_object_remove")
        self.gridLayout_18.addWidget(self.interface_element_object_remove, 2, 2, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_18)
        self.label_42 = QtWidgets.QLabel(self.pageObject)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_16.addWidget(self.label_42)
        self.interface_element_object_message = QtWidgets.QPlainTextEdit(self.pageObject)
        self.interface_element_object_message.setObjectName("interface_element_object_message")
        self.verticalLayout_16.addWidget(self.interface_element_object_message)
        self.stackedWidget.addWidget(self.pageObject)
        self.pageAnd = QtWidgets.QWidget()
        self.pageAnd.setObjectName("pageAnd")
        self.stackedWidget.addWidget(self.pageAnd)
        self.pageCheck = QtWidgets.QWidget()
        self.pageCheck.setObjectName("pageCheck")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageCheck)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.pageCheck)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.pageCheck)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.pageCheck)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.pageCheck)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.pageCheck)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.pageCheck)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.pageCheck)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 0, 1, 1, 1)
        self.interface_element_check_enemy = QtWidgets.QComboBox(self.pageCheck)
        self.interface_element_check_enemy.setObjectName("interface_element_check_enemy")
        self.interface_element_check_enemy.addItem("")
        self.interface_element_check_enemy.setItemText(0, "")
        self.interface_element_check_enemy.addItem("")
        self.interface_element_check_enemy.addItem("")
        self.gridLayout_6.addWidget(self.interface_element_check_enemy, 1, 2, 1, 1)
        self.interface_element_check_region_map = QtWidgets.QLineEdit(self.pageCheck)
        self.interface_element_check_region_map.setObjectName("interface_element_check_region_map")
        self.gridLayout_6.addWidget(self.interface_element_check_region_map, 0, 2, 1, 1)
        self.interface_element_check_started = QtWidgets.QLineEdit(self.pageCheck)
        self.interface_element_check_started.setObjectName("interface_element_check_started")
        self.gridLayout_6.addWidget(self.interface_element_check_started, 2, 2, 1, 1)
        self.interface_element_check_finished = QtWidgets.QLineEdit(self.pageCheck)
        self.interface_element_check_finished.setObjectName("interface_element_check_finished")
        self.gridLayout_6.addWidget(self.interface_element_check_finished, 3, 2, 1, 1)
        self.interface_element_check_completed = QtWidgets.QLineEdit(self.pageCheck)
        self.interface_element_check_completed.setObjectName("interface_element_check_completed")
        self.gridLayout_6.addWidget(self.interface_element_check_completed, 4, 2, 1, 1)
        self.interface_element_check_options = QtWidgets.QLineEdit(self.pageCheck)
        self.interface_element_check_options.setObjectName("interface_element_check_options")
        self.gridLayout_6.addWidget(self.interface_element_check_options, 6, 2, 1, 1)
        self.interface_element_check_num2finish = QtWidgets.QLineEdit(self.pageCheck)
        self.interface_element_check_num2finish.setObjectName("interface_element_check_num2finish")
        self.gridLayout_6.addWidget(self.interface_element_check_num2finish, 5, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.pageCheck)
        self.pageResponse = QtWidgets.QWidget()
        self.pageResponse.setObjectName("pageResponse")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageResponse)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_13 = QtWidgets.QLabel(self.pageResponse)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.interface_element_response_message = QtWidgets.QLineEdit(self.pageResponse)
        self.interface_element_response_message.setObjectName("interface_element_response_message")
        self.gridLayout_7.addWidget(self.interface_element_response_message, 1, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_15 = QtWidgets.QLabel(self.pageResponse)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 2, 0, 1, 1)
        self.interface_element_response_action = QtWidgets.QLineEdit(self.pageResponse)
        self.interface_element_response_action.setObjectName("interface_element_response_action")
        self.gridLayout_8.addWidget(self.interface_element_response_action, 2, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.pageResponse)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.interface_element_response_destination = QtWidgets.QComboBox(self.pageResponse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interface_element_response_destination.sizePolicy().hasHeightForWidth())
        self.interface_element_response_destination.setSizePolicy(sizePolicy)
        self.interface_element_response_destination.setEditable(True)
        self.interface_element_response_destination.setObjectName("interface_element_response_destination")
        self.gridLayout_8.addWidget(self.interface_element_response_destination, 0, 3, 1, 1)
        self.interface_button_dialog_destination = QtWidgets.QPushButton(self.pageResponse)
        self.interface_button_dialog_destination.setObjectName("interface_button_dialog_destination")
        self.gridLayout_8.addWidget(self.interface_button_dialog_destination, 1, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 2, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem10)
        self.stackedWidget.addWidget(self.pageResponse)
        self.pageAction = QtWidgets.QWidget()
        self.pageAction.setObjectName("pageAction")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageAction)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.interface_element_action_teleport = QtWidgets.QLineEdit(self.pageAction)
        self.interface_element_action_teleport.setObjectName("interface_element_action_teleport")
        self.gridLayout_11.addWidget(self.interface_element_action_teleport, 4, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.pageAction)
        self.label_40.setObjectName("label_40")
        self.gridLayout_11.addWidget(self.label_40, 4, 0, 1, 1)
        self.interface_element_action_start = QtWidgets.QLineEdit(self.pageAction)
        self.interface_element_action_start.setObjectName("interface_element_action_start")
        self.gridLayout_11.addWidget(self.interface_element_action_start, 1, 2, 1, 1)
        self.interface_element_action_complete = QtWidgets.QLineEdit(self.pageAction)
        self.interface_element_action_complete.setObjectName("interface_element_action_complete")
        self.gridLayout_11.addWidget(self.interface_element_action_complete, 2, 2, 1, 1)
        self.interface_element_action_region_map = QtWidgets.QLineEdit(self.pageAction)
        self.interface_element_action_region_map.setObjectName("interface_element_action_region_map")
        self.gridLayout_11.addWidget(self.interface_element_action_region_map, 0, 2, 1, 1)
        self.interface_element_action_enemy = QtWidgets.QComboBox(self.pageAction)
        self.interface_element_action_enemy.setObjectName("interface_element_action_enemy")
        self.interface_element_action_enemy.addItem("")
        self.interface_element_action_enemy.setItemText(0, "")
        self.interface_element_action_enemy.addItem("")
        self.interface_element_action_enemy.addItem("")
        self.gridLayout_11.addWidget(self.interface_element_action_enemy, 3, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem11, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.pageAction)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.pageAction)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.pageAction)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.pageAction)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.pageAction)
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 5, 0, 1, 1)
        self.interface_element_action_trigger = QtWidgets.QLineEdit(self.pageAction)
        self.interface_element_action_trigger.setObjectName("interface_element_action_trigger")
        self.gridLayout_11.addWidget(self.interface_element_action_trigger, 5, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_11)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_20 = QtWidgets.QLabel(self.pageAction)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 0, 0, 1, 1)
        self.interface_element_action_text = QtWidgets.QPlainTextEdit(self.pageAction)
        self.interface_element_action_text.setTabStopWidth(16)
        self.interface_element_action_text.setObjectName("interface_element_action_text")
        self.gridLayout_12.addWidget(self.interface_element_action_text, 1, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_12)
        self.stackedWidget.addWidget(self.pageAction)
        self.pageNotification = QtWidgets.QWidget()
        self.pageNotification.setObjectName("pageNotification")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pageNotification)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem12, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.pageNotification)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.pageNotification)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.pageNotification)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.pageNotification)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 1, 0, 1, 1)
        self.interface_element_notification_message = QtWidgets.QLineEdit(self.pageNotification)
        self.interface_element_notification_message.setObjectName("interface_element_notification_message")
        self.gridLayout_13.addWidget(self.interface_element_notification_message, 0, 2, 1, 1)
        self.interface_element_notification_action = QtWidgets.QLineEdit(self.pageNotification)
        self.interface_element_notification_action.setObjectName("interface_element_notification_action")
        self.gridLayout_13.addWidget(self.interface_element_notification_action, 1, 2, 1, 1)
        self.interface_element_notification_shortcut = QtWidgets.QLineEdit(self.pageNotification)
        self.interface_element_notification_shortcut.setObjectName("interface_element_notification_shortcut")
        self.gridLayout_13.addWidget(self.interface_element_notification_shortcut, 2, 2, 1, 1)
        self.interface_element_notification_delay = QtWidgets.QLineEdit(self.pageNotification)
        self.interface_element_notification_delay.setObjectName("interface_element_notification_delay")
        self.gridLayout_13.addWidget(self.interface_element_notification_delay, 3, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_13)
        spacerItem13 = QtWidgets.QSpacerItem(20, 391, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.stackedWidget.addWidget(self.pageNotification)
        self.pageInherit = QtWidgets.QWidget()
        self.pageInherit.setObjectName("pageInherit")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageInherit)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem14, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.pageInherit)
        self.label_25.setObjectName("label_25")
        self.gridLayout_14.addWidget(self.label_25, 0, 0, 1, 1)
        self.interface_element_inherit_name = QtWidgets.QLineEdit(self.pageInherit)
        self.interface_element_inherit_name.setObjectName("interface_element_inherit_name")
        self.gridLayout_14.addWidget(self.interface_element_inherit_name, 0, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 531, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem15)
        self.stackedWidget.addWidget(self.pageInherit)
        self.pageQuest = QtWidgets.QWidget()
        self.pageQuest.setObjectName("pageQuest")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageQuest)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.pageQuest)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.interface_element_quest_name = QtWidgets.QLineEdit(self.pageQuest)
        self.interface_element_quest_name.setObjectName("interface_element_quest_name")
        self.gridLayout_4.addWidget(self.interface_element_quest_name, 0, 3, 1, 1)
        self.interface_element_quest_repeat = QtWidgets.QCheckBox(self.pageQuest)
        self.interface_element_quest_repeat.setObjectName("interface_element_quest_repeat")
        self.gridLayout_4.addWidget(self.interface_element_quest_repeat, 1, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.pageQuest)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 2, 1, 1, 1)
        self.interface_element_quest_repeat_delay = QtWidgets.QLineEdit(self.pageQuest)
        self.interface_element_quest_repeat_delay.setObjectName("interface_element_quest_repeat_delay")
        self.gridLayout_4.addWidget(self.interface_element_quest_repeat_delay, 2, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem17)
        self.stackedWidget.addWidget(self.pageQuest)
        self.pageMessage = QtWidgets.QWidget()
        self.pageMessage.setObjectName("pageMessage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageMessage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.interface_element_message_text = QtWidgets.QPlainTextEdit(self.pageMessage)
        self.interface_element_message_text.setObjectName("interface_element_message_text")
        self.gridLayout_3.addWidget(self.interface_element_message_text, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.pageMessage)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.pageMessage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 0, 1, 1, 1)
        self.interface_element_message_color = QtWidgets.QComboBox(self.pageMessage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interface_element_message_color.sizePolicy().hasHeightForWidth())
        self.interface_element_message_color.setSizePolicy(sizePolicy)
        self.interface_element_message_color.setEditable(True)
        self.interface_element_message_color.setObjectName("interface_element_message_color")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.interface_element_message_color.addItem("")
        self.gridLayout_5.addWidget(self.interface_element_message_color, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.stackedWidget.addWidget(self.pageMessage)
        self.pageDialog = QtWidgets.QWidget()
        self.pageDialog.setObjectName("pageDialog")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.pageDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.interface_element_dialog_name = QtWidgets.QLineEdit(self.pageDialog)
        self.interface_element_dialog_name.setObjectName("interface_element_dialog_name")
        self.gridLayout.addWidget(self.interface_element_dialog_name, 0, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.pageDialog)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 3, 0, 1, 1)
        self.interface_element_dialog_icon = QtWidgets.QLineEdit(self.pageDialog)
        self.interface_element_dialog_icon.setObjectName("interface_element_dialog_icon")
        self.gridLayout.addWidget(self.interface_element_dialog_icon, 3, 2, 1, 1)
        self.interface_element_dialog_title = QtWidgets.QLineEdit(self.pageDialog)
        self.interface_element_dialog_title.setObjectName("interface_element_dialog_title")
        self.gridLayout.addWidget(self.interface_element_dialog_title, 4, 2, 1, 1)
        self.interface_element_dialog_inherit = QtWidgets.QLineEdit(self.pageDialog)
        self.interface_element_dialog_inherit.setObjectName("interface_element_dialog_inherit")
        self.gridLayout.addWidget(self.interface_element_dialog_inherit, 2, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.pageDialog)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 2, 0, 1, 1)
        self.interface_element_dialog_regex = QtWidgets.QLineEdit(self.pageDialog)
        self.interface_element_dialog_regex.setObjectName("interface_element_dialog_regex")
        self.gridLayout.addWidget(self.interface_element_dialog_regex, 1, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.pageDialog)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.pageDialog)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 5, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.pageDialog)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 4, 0, 1, 1)
        self.interface_element_dialog_animation = QtWidgets.QLineEdit(self.pageDialog)
        self.interface_element_dialog_animation.setObjectName("interface_element_dialog_animation")
        self.gridLayout.addWidget(self.interface_element_dialog_animation, 5, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem20)
        self.stackedWidget.addWidget(self.pageDialog)
        self.pageInterface = QtWidgets.QWidget()
        self.pageInterface.setObjectName("pageInterface")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageInterface)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.pageInterface)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 0, 1, 1, 1)
        self.interface_element_interface_state = QtWidgets.QComboBox(self.pageInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interface_element_interface_state.sizePolicy().hasHeightForWidth())
        self.interface_element_interface_state.setSizePolicy(sizePolicy)
        self.interface_element_interface_state.setEditable(True)
        self.interface_element_interface_state.setObjectName("interface_element_interface_state")
        self.interface_element_interface_state.addItem("")
        self.interface_element_interface_state.setItemText(0, "")
        self.interface_element_interface_state.addItem("")
        self.interface_element_interface_state.addItem("")
        self.gridLayout_2.addWidget(self.interface_element_interface_state, 0, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.pageInterface)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 1, 0, 1, 1)
        self.interface_element_interface_npc = QtWidgets.QLineEdit(self.pageInterface)
        self.interface_element_interface_npc.setObjectName("interface_element_interface_npc")
        self.gridLayout_2.addWidget(self.interface_element_interface_npc, 1, 2, 1, 1)
        self.interface_element_interface_inherit = QtWidgets.QLineEdit(self.pageInterface)
        self.interface_element_interface_inherit.setObjectName("interface_element_interface_inherit")
        self.gridLayout_2.addWidget(self.interface_element_interface_inherit, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.pageInterface)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem22)
        self.stackedWidget.addWidget(self.pageInterface)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.splitter)
        WindowInterfaceEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowInterfaceEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 21))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        WindowInterfaceEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowInterfaceEditor)
        self.statusbar.setObjectName("statusbar")
        WindowInterfaceEditor.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(WindowInterfaceEditor)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(WindowInterfaceEditor)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(WindowInterfaceEditor)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(WindowInterfaceEditor)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionUndo = QtWidgets.QAction(WindowInterfaceEditor)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(WindowInterfaceEditor)
        self.actionRedo.setObjectName("actionRedo")
        self.menuTest.addAction(self.actionNew)
        self.menuTest.addAction(self.actionOpen)
        self.menuTest.addAction(self.actionSave)
        self.menuTest.addAction(self.actionSave_As)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(WindowInterfaceEditor)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WindowInterfaceEditor)

    def retranslateUi(self, WindowInterfaceEditor):
        _translate = QtCore.QCoreApplication.translate
        WindowInterfaceEditor.setWindowTitle(_translate("WindowInterfaceEditor", "Interface Editor"))
        self.label_37.setText(_translate("WindowInterfaceEditor", "Message"))
        self.label_35.setText(_translate("WindowInterfaceEditor", "Number to kill"))
        self.label_26.setText(_translate("WindowInterfaceEditor", "UID"))
        self.label_27.setText(_translate("WindowInterfaceEditor", "Name"))
        self.label_28.setText(_translate("WindowInterfaceEditor", "Quest information"))
        self.label_29.setText(_translate("WindowInterfaceEditor", "Arch name"))
        self.label_31.setText(_translate("WindowInterfaceEditor", "Number"))
        self.label_30.setText(_translate("WindowInterfaceEditor", "Name"))
        self.interface_element_item_keep.setText(_translate("WindowInterfaceEditor", "Keep item"))
        self.label_33.setText(_translate("WindowInterfaceEditor", "Name"))
        self.label_32.setText(_translate("WindowInterfaceEditor", "Arch name"))
        self.label_41.setText(_translate("WindowInterfaceEditor", "Number to remove"))
        self.label_42.setText(_translate("WindowInterfaceEditor", "Message"))
        self.label_9.setText(_translate("WindowInterfaceEditor", "Finished"))
        self.label_11.setText(_translate("WindowInterfaceEditor", "Options"))
        self.label_12.setText(_translate("WindowInterfaceEditor", "Number to finish"))
        self.label_7.setText(_translate("WindowInterfaceEditor", "Enemy"))
        self.label_8.setText(_translate("WindowInterfaceEditor", "Started"))
        self.label_6.setText(_translate("WindowInterfaceEditor", "Region map"))
        self.label_10.setText(_translate("WindowInterfaceEditor", "Completed"))
        self.interface_element_check_enemy.setItemText(1, _translate("WindowInterfaceEditor", "any"))
        self.interface_element_check_enemy.setItemText(2, _translate("WindowInterfaceEditor", "player"))
        self.label_13.setText(_translate("WindowInterfaceEditor", "Message"))
        self.label_15.setText(_translate("WindowInterfaceEditor", "Action"))
        self.label_14.setText(_translate("WindowInterfaceEditor", "Dialog destination"))
        self.interface_button_dialog_destination.setText(_translate("WindowInterfaceEditor", "Enter dialog"))
        self.label_40.setText(_translate("WindowInterfaceEditor", "Teleport"))
        self.interface_element_action_enemy.setItemText(1, _translate("WindowInterfaceEditor", "player"))
        self.interface_element_action_enemy.setItemText(2, _translate("WindowInterfaceEditor", "clear"))
        self.label_16.setText(_translate("WindowInterfaceEditor", "Region Map"))
        self.label_18.setText(_translate("WindowInterfaceEditor", "Complete"))
        self.label_17.setText(_translate("WindowInterfaceEditor", "Start"))
        self.label_19.setText(_translate("WindowInterfaceEditor", "Enemy"))
        self.label_45.setText(_translate("WindowInterfaceEditor", "Trigger"))
        self.label_20.setText(_translate("WindowInterfaceEditor", "Code"))
        self.label_24.setText(_translate("WindowInterfaceEditor", "Delay"))
        self.label_21.setText(_translate("WindowInterfaceEditor", "Message"))
        self.label_23.setText(_translate("WindowInterfaceEditor", "Shortcut"))
        self.label_22.setText(_translate("WindowInterfaceEditor", "Action"))
        self.label_25.setText(_translate("WindowInterfaceEditor", "Dialog name to inherit"))
        self.label_2.setText(_translate("WindowInterfaceEditor", "Quest name"))
        self.interface_element_quest_repeat.setText(_translate("WindowInterfaceEditor", "Repeatable"))
        self.label_46.setText(_translate("WindowInterfaceEditor", "Repeat delay"))
        self.label_4.setText(_translate("WindowInterfaceEditor", "Message"))
        self.label_5.setText(_translate("WindowInterfaceEditor", "Color"))
        self.interface_element_message_color.setItemText(0, _translate("WindowInterfaceEditor", "white"))
        self.interface_element_message_color.setItemText(1, _translate("WindowInterfaceEditor", "orange"))
        self.interface_element_message_color.setItemText(2, _translate("WindowInterfaceEditor", "navy"))
        self.interface_element_message_color.setItemText(3, _translate("WindowInterfaceEditor", "red"))
        self.interface_element_message_color.setItemText(4, _translate("WindowInterfaceEditor", "green"))
        self.interface_element_message_color.setItemText(5, _translate("WindowInterfaceEditor", "blue"))
        self.interface_element_message_color.setItemText(6, _translate("WindowInterfaceEditor", "gray"))
        self.interface_element_message_color.setItemText(7, _translate("WindowInterfaceEditor", "brown"))
        self.interface_element_message_color.setItemText(8, _translate("WindowInterfaceEditor", "purple"))
        self.interface_element_message_color.setItemText(9, _translate("WindowInterfaceEditor", "pink"))
        self.interface_element_message_color.setItemText(10, _translate("WindowInterfaceEditor", "yellow"))
        self.interface_element_message_color.setItemText(11, _translate("WindowInterfaceEditor", "dk_navy"))
        self.interface_element_message_color.setItemText(12, _translate("WindowInterfaceEditor", "dk_green"))
        self.interface_element_message_color.setItemText(13, _translate("WindowInterfaceEditor", "dk_orange"))
        self.interface_element_message_color.setItemText(14, _translate("WindowInterfaceEditor", "hgold"))
        self.interface_element_message_color.setItemText(15, _translate("WindowInterfaceEditor", "dgold"))
        self.label_3.setText(_translate("WindowInterfaceEditor", "Dialog identifier"))
        self.label_43.setText(_translate("WindowInterfaceEditor", "Icon"))
        self.label_39.setText(_translate("WindowInterfaceEditor", "Inherit"))
        self.label_38.setText(_translate("WindowInterfaceEditor", "Regex"))
        self.label_47.setText(_translate("WindowInterfaceEditor", "Animation"))
        self.label_44.setText(_translate("WindowInterfaceEditor", "Title"))
        self.label.setText(_translate("WindowInterfaceEditor", "Interface state"))
        self.interface_element_interface_state.setItemText(1, _translate("WindowInterfaceEditor", "completed"))
        self.interface_element_interface_state.setItemText(2, _translate("WindowInterfaceEditor", "finished"))
        self.label_34.setText(_translate("WindowInterfaceEditor", "NPC"))
        self.label_36.setText(_translate("WindowInterfaceEditor", "Inherit"))
        self.menuTest.setTitle(_translate("WindowInterfaceEditor", "File"))
        self.menuEdit.setTitle(_translate("WindowInterfaceEditor", "Edit"))
        self.actionNew.setText(_translate("WindowInterfaceEditor", "New"))
        self.actionNew.setShortcut(_translate("WindowInterfaceEditor", "Ctrl+N"))
        self.actionOpen.setText(_translate("WindowInterfaceEditor", "Open"))
        self.actionOpen.setShortcut(_translate("WindowInterfaceEditor", "Ctrl+O"))
        self.actionSave.setText(_translate("WindowInterfaceEditor", "Save"))
        self.actionSave.setShortcut(_translate("WindowInterfaceEditor", "Ctrl+S"))
        self.actionSave_As.setText(_translate("WindowInterfaceEditor", "Save As"))
        self.actionSave_As.setShortcut(_translate("WindowInterfaceEditor", "Ctrl+Shift+S"))
        self.actionUndo.setText(_translate("WindowInterfaceEditor", "Undo"))
        self.actionUndo.setShortcut(_translate("WindowInterfaceEditor", "Ctrl+Z"))
        self.actionRedo.setText(_translate("WindowInterfaceEditor", "Redo"))
        self.actionRedo.setShortcut(_translate("WindowInterfaceEditor", "Ctrl+Shift+Z"))

