#!/usr/bin/env bash
set -euo pipefail

# windows-build:0.0.3 contains MXE's compiler drivers and CMake wrapper here.
# Login shells can replace PATH, so restore the directory when necessary.
if [[ -d /opt/mxe/usr/bin && ":${PATH}:" != *":/opt/mxe/usr/bin:"* ]]; then
    export PATH="/opt/mxe/usr/bin:${PATH}"
fi

if [[ -z "${MXE_TOOLCHAIN_FILE:-}" || ! -f "${MXE_TOOLCHAIN_FILE}" ]]; then
    echo "MXE_TOOLCHAIN_FILE does not point to an MXE toolchain." >&2
    echo "Run this script in the 'Atrinik Windows cross-build (MXE)' devcontainer." >&2
    exit 1
fi

if [[ -z "${MXE_RUNTIME_DIR:-}" || ! -d "${MXE_RUNTIME_DIR}" ]]; then
    echo "MXE_RUNTIME_DIR does not point to the shared MXE runtime directory." >&2
    exit 1
fi

MXE_CMAKE="${MXE_TARGET:-x86_64-w64-mingw32.shared}-cmake"
if ! command -v "${MXE_CMAKE}" >/dev/null; then
    echo "MXE CMake wrapper is unavailable: ${MXE_CMAKE}" >&2
    exit 1
fi

JOBS=${JOBS:-$(nproc)}
PACKAGE_DIR=${PACKAGE_DIR:-build/packages}
TARGET=${1:-all}
SERVER_BUILD_DIR=build/windows-mxe-server-release
SERVER_PACKAGE_ROOT=${SERVER_BUILD_DIR}/package-root
REGION_BUILD_DIR=build/windows-region-map-generator
REGION_RUNTIME_DIR=${SERVER_PACKAGE_ROOT}/region-runtime
REGION_DATA_DIR=${SERVER_PACKAGE_ROOT}/worldmaker-data
REPOSITORY_ROOT=$(pwd)

case "${TARGET}" in
    all|client|server) ;;
    *)
        echo "Usage: $0 [all|client|server]" >&2
        exit 2
        ;;
esac

case "${SERVER_PACKAGE_ROOT}" in
    build/windows-mxe-server-release/package-root) ;;
    *)
        echo "Refusing to replace unexpected package staging path: ${SERVER_PACKAGE_ROOT}" >&2
        exit 1
        ;;
esac

prepare_server_content() {
    local content_hash cached_hash=""
    local region_cmake_args=(
        -S .
        -B "${REGION_BUILD_DIR}"
        -DCMAKE_BUILD_TYPE=Release
        -DPACKAGE_TYPE=none
        -DBUILD_CLIENT=OFF
        -DBUILD_SERVER=ON
    )
    if command -v ccache >/dev/null; then
        region_cmake_args+=(
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
        )
    fi

    content_hash=$(
        {
            find arch maps server/install_data server/resources server/src \
                common/toolkit tools/compilers \
                -type f \
                ! -path '*/__pycache__/*' \
                ! -name '*.pyc' \
                ! -name '*.pyo' \
                -print0
            printf '%s\0' \
                CMakeLists.txt \
                CMakePresets.json \
                build-windows.sh \
                build.config \
                common/toolkit/CMakeLists.txt \
                server/CMakeLists.txt \
                server/server.cfg \
                server/permissions.cfg \
                tools/collect.py \
                tools/utils.py
        } \
            | sort -z \
            | xargs -0 sha256sum \
            | sha256sum \
            | cut -d ' ' -f 1
    )
    if [[ -f "${SERVER_PACKAGE_ROOT}/content.sha256" ]]; then
        cached_hash=$(<"${SERVER_PACKAGE_ROOT}/content.sha256")
    fi
    if [[ "${content_hash}" == "${cached_hash}" &&
            -d "${SERVER_PACKAGE_ROOT}/lib" &&
            -d "${SERVER_PACKAGE_ROOT}/client-maps" ]]; then
        echo "Reusing content-addressed server collection and region maps."
        return
    fi

    cmake -E remove_directory "${SERVER_PACKAGE_ROOT}"
    cmake -E make_directory "${SERVER_PACKAGE_ROOT}"
    cmake -E copy_directory arch "${SERVER_PACKAGE_ROOT}/arch"
    cmake -E copy_directory maps "${SERVER_PACKAGE_ROOT}/maps"
    cmake -E make_directory "${SERVER_PACKAGE_ROOT}/lib"
    python3 tools/collect.py \
        --dir "${SERVER_PACKAGE_ROOT}" \
        --out "${SERVER_PACKAGE_ROOT}/lib"

    # Region maps are generated by a native Linux server because the MinGW
    # binary cannot run in the cross-build container. Keep mutable data in
    # package staging; never use or modify server/data.
    /usr/bin/cmake "${region_cmake_args[@]}"
    /usr/bin/cmake --build "${REGION_BUILD_DIR}" \
        --target atrinik-server plugin_arena \
        --parallel "${JOBS}"

    cmake -E make_directory "${REGION_RUNTIME_DIR}"
    cmake -E copy \
        "${REGION_BUILD_DIR}/server/atrinik-server" \
        "${REGION_BUILD_DIR}/server/libplugin_arena.so" \
        "${REGION_BUILD_DIR}/server/libplugin_python.so" \
        server/server.cfg \
        server/permissions.cfg \
        "${REGION_RUNTIME_DIR}"
    cmake -E copy_directory server/install_data "${REGION_DATA_DIR}"
    cmake -E make_directory \
        "${REGION_DATA_DIR}/tmp" \
        "${REGION_DATA_DIR}/http"

    (
        cd "${REGION_RUNTIME_DIR}"
        ./atrinik-server \
            --worldmaker \
            --libpath="${REPOSITORY_ROOT}/${SERVER_PACKAGE_ROOT}/lib" \
            --mapspath="${REPOSITORY_ROOT}/${SERVER_PACKAGE_ROOT}/maps" \
            --datapath="${REPOSITORY_ROOT}/${REGION_DATA_DIR}" \
            --httppath="${REPOSITORY_ROOT}/${REGION_DATA_DIR}/http" \
            --resourcespath="${REPOSITORY_ROOT}/server/resources" \
            --http_server=off
    )

    cmake -E copy_directory \
        "${REGION_DATA_DIR}/http/client-maps" \
        "${SERVER_PACKAGE_ROOT}/client-maps"
    local map_count
    map_count=$(find "${SERVER_PACKAGE_ROOT}/client-maps" \
        -maxdepth 1 -type f -name '*.png' | wc -l)
    if [[ "${map_count}" -eq 0 ]]; then
        echo "The native world maker did not generate any region maps." >&2
        exit 1
    fi
    echo "Generated ${map_count} region maps for the Windows server package."
    printf '%s\n' "${content_hash}" > "${SERVER_PACKAGE_ROOT}/content.sha256"
    cmake -E remove_directory "${REGION_RUNTIME_DIR}"
    cmake -E remove_directory "${REGION_DATA_DIR}"
}

mkdir -p "${PACKAGE_DIR}"
if [[ "${TARGET}" == all || "${TARGET}" == client ]]; then
    "${MXE_CMAKE}" --no-warn-unused-cli --preset windows-mxe-release
    cmake --build --preset windows-mxe-release --parallel "${JOBS}"
    cpack --config build/windows-mxe-release/CPackConfig.cmake \
        -G ZIP \
        -B "${PACKAGE_DIR}"
fi
if [[ "${TARGET}" == all || "${TARGET}" == server ]]; then
    prepare_server_content
    "${MXE_CMAKE}" --no-warn-unused-cli --preset windows-mxe-server-release
    cmake --build --preset windows-mxe-server-release --parallel "${JOBS}"
    cpack --config build/windows-mxe-server-release/CPackConfig.cmake \
        -G ZIP \
        -B "${PACKAGE_DIR}"
fi

echo "Windows ${TARGET} package target written to ${PACKAGE_DIR}"
